name: manage-azure-policy-79f95c2c
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'intiative/initiatives/Non_Prod_MTB_Monitoring_Initiative_Monitoring-Policies/**'
#      - .github/workflows/manage-azure-policy-79f95c2c.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_79f95c2c}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          intiative/initiatives/Non_Prod_MTB_Monitoring_Initiative_Monitoring-Policies/**
